ALTER TABLE dentist
    MODIFY COLUMN first_name NVARCHAR(255) NOT NULL ;

ALTER TABLE dentist
  MODIFY COLUMN last_name NVARCHAR(255) NOT NULL ;

ALTER TABLE dentist
  MODIFY COLUMN middle_name NVARCHAR(255) NULL ;